### ISSUE TITLE
Won't build under TKL Core

### ISSUE THREAD

**Issue by ibm2100** [crosbymichael/slex#2]
I installed Turnkey Linux Core 13.0 / Debian 7.2 Wheezy on VirtualBox under Windows 7, 64-bit.

When I issued the command go build main.go, these are the errors:

./main.go:60: undefined: newCommand
./main.go:85: undefined: command
./main.go:105: undefined: command
./main.go:106: undefined: newSshClientConfig
./main.go:118: undefined: newNameWriter
./main.go:119: undefined: newNameWriter

However, it is building fine under Windows 7 using go1.3.3 windows/386

I am using go1.3.3 linux/amd64 on my VirtualBox VM.

**Comment by vieux** [comment]
@ibm2100 you should use `go build` instead fo `go build main.go` the code is divided in 3 files.

Most of you undefined stuff are defined in `ssh.go`

**Comment by crosbymichael** [comment]
Thanks for looking into this @vieux
